// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tienda.Models;

namespace Tienda.Migrations
{
    [DbContext(typeof(TiendaContext))]
    partial class TiendaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tienda.Models.Categoria", b =>
            {
                b.Property<int>("CategoriaID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<DateTime>("Fecha")
                    .HasColumnType("datetime2");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasColumnType("nvarchar(50)")
                    .HasMaxLength(50);

                b.HasKey("CategoriaID");

                b.ToTable("Categoria");
            });

            modelBuilder.Entity("Tienda.Models.Product", b =>
            {
                b.Property<int>("ProductID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int?>("CategoriaID")
                    .HasColumnType("int");

                b.Property<string>("Desc")
                    .HasColumnType("nvarchar(500)")
                    .HasMaxLength(500);

                b.Property<DateTime>("Fecha")
                    .HasColumnType("datetime2");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasColumnType("nvarchar(50)")
                    .HasMaxLength(50);

                b.HasKey("ProductID");

                b.HasIndex("CategoriaID");

                b.ToTable("Product");
            });

            modelBuilder.Entity("Tienda.Models.Product", b =>
            {
                b.HasOne("Tienda.Models.Categoria", "Categoria")
                    .WithMany()
                    .HasForeignKey("CategoriaID");
            });
#pragma warning restore 612, 618
        }
    }
}
